### PR TITLE
Add datepicker library

### PR DESCRIPTION
**Pull request by SimonDEvans**
Including a datepicker by default in order to avoid:

- Wasting time adding a datepicker on almost every project
- Maintaining multiple datepicker libraries across our codebases
- Introducing disorganised vendor CSS each time we need a datepicker

I've chosen [this library](https://github.com/dbushell/Pikaday) because:

- Lotsa github stars
- Plenty of [config options](https://github.com/dbushell/Pikaday#configuration)
- Easy to modify and extend
- Nice to implement (ES6 class)
- Decent browser support (IE 7+)
- No jQuery dependency

Drawbacks:

 - This adds the library as a dependency in `package.json` and styling in `sass/vendor`, so
 removing it wouldn't be as easy as deleting a pattern

Since this isn't really a component or a pattern itself, I've attached it to the form-builder molecule for now.

### CODE REVIEW

**Comment by SimonDEvans** [comment]
@helenb I've defined some base vars [here](https://github.com/torchbox/design-in-browser-bootstrap/pull/62/files#diff-5544bc77a85c704a41a5253447554ded) which should be good enough for now.

**Comment by nicklee** [comment]
Looks great to me, keyboard nav doesn't currently work when installed via npm, but there's already an issue open, so should be fixed when we next need to use this :)

https://github.com/dbushell/Pikaday/issues/732

**Comment by SimonDEvans** [comment]
Thanks both, merging...

**Comment by helenb** [comment]
@SimonDEvans ah ok - I assumed they were part of the vendor css. I would advise copying the vendor css without any changes into the vendor folder - so it can easily be updated - and add our own overrides to a separate file.

**Comment by SimonDEvans** [comment]
Hmm, good point. I guess the only problem is that vendor CSS is included before anything else (even before `variables.scss`, so we'd have to change things up a bit. Will explore next time I use this on a production build!

**Pull request merged**
