### PR TITLE
ES6 imports

### PR DESCRIPTION
**Pull request by balazs-endresz**
A few minor things need to be sorted out before merging but if you could give this a try that would be great. This would be very useful for django/wagtail projects that use a lot of javascript, so DIBB should be as close to it as possible. It was also easier to try these in DIBB instead of wagtail-kit but that should eventually use ES6 imports too.

- [x] use ES6 imports with rollup+babel
- [x] allow using node modules on the website if they are specified in package.json devDependencies
- [x] expose jQuery globally
- [x] allow importing older, non-ES6 jQuery plugins
- [x] add `point.js` to demonstrate how to import ES6 modules from /static/js/
- [x] enable source maps
- [x] use uglifyjs
- [x] upgrade packages
- [x] add yarn.lock file
- [x] add instructions for using yarn (1. only install modules with yarn 2. make sure yarn.lock is updated when updating packages: this ensures we don't get dependency conflicts 3. `npm` still can be used for npm scripts, although `yarn run ...` seems to work too, not sure what's the difference there)
- [x] Should we define `globals` in `package.json`? It doesn't seem to make any difference. see: https://github.com/balazs-endresz/design-in-browser-bootstrap/blob/es6-imports/rollup.config.js#L27 And perhaps related to this, rollup doesn't display a warning if we're using undefined variables. -> `rollup-plugin-eslint` now, and added note about specifying globals in .eslintrc instead
- [x] `npm run lint:js` does show warnings about undefined variables but doesn't realise that `window.jQuery` is a global one. Also, that's currently not run during `npm run dev`. -> using `rollup-plugin-eslint` now that always runs eslint
- [ ] Do we need to add `exclude: 'node_modules/**'`? That seems to be a common thing to do but maybe only necessary if we had `entry: "**.js"` in `rollup.config.js`?
- [x] Run uglifyjs for the production build only, or just disable it because it's not really need here.
- [x] In `package.json` we have `"node": ">=4 <6"`. Why is it `<6`? And why does it run on node v6+ anyway without even a warning? -> It's just `"node": ">=4"` but node is not strict about it anyway, so it's just for documenting what works really.
- [x] How does one specify multiple files in `rollup.config.js`, not just `dist/js/main.js`? That would be important on sites like upshot that have multiple js bundles but maybe not so much on a typical wagtail site. -> https://github.com/rollup/rollup/issues/703
- [x] run linting from either rollup or from `lint:js` - some commands run both
- [x] display file size information
- [ ] including large files, like jquery makes rollup very slow: see if it can be cached, or if we can disable tree shaking, or include it from a cdn

### CODE REVIEW

**Comment by Loque-** [comment]
Thanks so much Balazs, going through it now!

**Comment by Loque-** [comment]
Hey, I am so sorry for not merging this before. Thanks again for the work on it - very cool. Looking forward to using the adjustments. Thank you!

**Comment by balazs-endresz** [comment]
Thanks Toby but speed might be an issue because it's doing tree shaking on jquery as well. There are a couple of ways to optimise that:

* making rollup watch changes: https://github.com/rollup/rollup/issues/191#issuecomment-224986002
* or adding a cache object: https://github.com/rollup/rollup/wiki/JavaScript-API

We could also include jquery separately instead of importing it but I wanted to investigate the caching first.

Does it not take much more time for you to rebuild everything when you change some javascript?

**Comment by balazs-endresz** [comment]
Using `rollup -w` improves performance by 70% for me but we can't run `postbuild:js` if we use rollup to watch for changes. And the `cache` option cannot be used with a `rollup.config.js` config file, so we'd have to use either use the javascript API instead: https://github.com/rollup/rollup/wiki/JavaScript-API or figure out how to make caching work from `rollup.config.js`.

**Pull request merged**
